name: Daily Auto Commit

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update timestamp
        run: |
          echo "Update: $(date)" >> log.txt

      - name: Commit and Push
        run: |
          git config --global user.name "Mohammed Saad Affan"
          git config --global user.email "saadaffan129@gmail.com"
          git add .
          git commit -m "Daily automated commit" || echo "No changes to commit"
          git push
